/**
 * Render `evidence/measurements.json` as the generated half of `docs/MEASUREMENTS.md`. Pure, so the
 * document is reproducible from the JSON alone and the renderer is unit-tested.
 */

import type { Measurements } from "./collect";
import type { Fit, Fit2, Summary } from "./stats";

export const START = "<!-- measurements:start (generated by `bun run worker/src/cli.ts measure`; do not edit by hand) -->";
export const END = "<!-- measurements:end -->";

const int = (v: number | null | undefined) => (v === null || v === undefined || !Number.isFinite(v) ? "—" : Math.round(v).toLocaleString("en-US"));
const dur = (s: number | null | undefined) => {
  if (s === null || s === undefined) return "—";
  if (s < 90) return `${Math.round(s)} s`;
  if (s < 5400) return `${(s / 60).toFixed(1)} min`;
  return `${(s / 3600).toFixed(2)} h`;
};
const pct = (v: number) => `${(v * 100).toFixed(2)}%`;
const fit = (f: Fit | null, x: string, y = "gas") =>
  f ? `${y} ≈ ${int(f.intercept)} + ${int(f.slope)} · ${x} (R² ${f.r2.toFixed(3)}, ${f.n} points)` : "not enough distinct points to fit";
const fit2 = (f: Fit2 | null, x1: string, x2: string) =>
  f
    ? `gas ≈ ${int(f.intercept)} + ${int(f.b1)} · ${x1} + ${f.b2.toFixed(1)} · ${x2} (R² ${f.r2.toFixed(3)}, ${f.n} points)`
    : "not enough independent points to fit";
const summaryRow = (label: string, s: Summary | null, fmt: (v: number) => string) =>
  s ? `| ${label} | ${s.count} | ${fmt(s.min)} | ${fmt(s.p50)} | ${fmt(s.p90)} | ${fmt(s.max)} |` : `| ${label} | 0 | — | — | — | — |`;
const short = (a: string) => (a.startsWith("0x") && a.length === 42 ? `\`${a.slice(0, 8)}…${a.slice(-4)}\`` : a);

export function renderMeasurements(m: Measurements): string {
  const lines: string[] = [];
  const push = (...l: string[]) => lines.push(...l);

  push(
    START,
    "",
    `_Collected ${m.generatedAt} from CC3 testnet (chainId ${m.cc3.chainId}) at block ${int(m.cc3.head)}; block gas limit ${int(m.cc3.blockGasLimit)}._`,
    "",
    "### Gas per batch size",
    "",
    "Every real relay transaction on both `AttestedWorldID` instances since deployment, grouped by how many",
    "World ID updates it carried.",
    "",
    "| Updates in the batch | Transactions | Min gas | Median gas | Max gas |",
    "|---:|---:|---:|---:|---:|",
    ...m.gasByBatchSize.map((r) => `| ${r.n} | ${r.observed} | ${int(r.min)} | ${int(r.median)} | ${int(r.max)} |`),
    "",
    `- Live fit on batch size alone: ${fit(m.liveFit, "updates")}.`,
    `- Live fit with the continuity span: ${fit2(m.liveModel, "updates", "continuity roots")}.`,
    "",
    "Live batches only cover the sizes the relay happened to need, so sizes up to the cap are measured on a",
    "fresh copy of the live relay bytecode (an `eth_call` state override) fed consecutive real Sepolia",
    `updates, with gas read by \`contracts/script/GasProbe.sol\`. ${m.probe.note}`,
    "",
    "| Updates | Continuity roots | Calldata bytes | Execution gas | Transaction gas | Result |",
    "|---:|---:|---:|---:|---:|---|",
    ...m.probe.points.map(
      (p) => `| ${p.n} | ${int(p.continuityRoots)} | ${int(p.calldataBytes)} | ${int(p.executionGas)} | ${int(p.txGas)} | ${p.ok ? "adopted" : (p.error ?? "refused")} |`,
    ),
    "",
    `- Probe fit: ${fit(m.probe.fit, "updates")}.`,
    `- Probe fit with the continuity span: ${fit2(m.probe.model, "updates", "continuity roots")}.`,
    "- The first update on a fresh copy is a bootstrap and records two roots, so n = 1 costs slightly more than a steady-state single relay.",
    "",
    "### The 10 / 11 cap",
    "",
    `- 11 updates: \`${m.cap.elevenError ?? "—"}\`, refused before any proof work.`,
    `- 10 updates: passes the size check and is refused later, by \`${m.cap.tenError ?? "—"}\` (the probe reuses an already-relayed update), which is what proves the cap is exactly 10.`,
    `- Projected gas for a full batch of 10: ${int(m.cap.projectedGasAt10)}, which fits ${m.cap.headroomAt10 ?? "—"} times in one CC3 block.`,
    "",
    "### Attestation vs checkpoint",
    "",
    `- Reading the attestation tip (\`get_latest_attestation_height_and_hash\`): ${int(m.anchors.attestationReadGas)} gas.`,
    `- Reading the checkpoint tip (\`get_latest_checkpoint_height_and_hash\`): ${int(m.anchors.checkpointReadGas)} gas.`,
    "",
    "`0x0FD2` `verify` gas for real proofs, by what the continuity chain is anchored to:",
    "",
    "| Source tx | Chain key | Anchor | Continuity roots | Verify gas |",
    "|---|---:|---|---:|---:|",
    ...m.anchors.verify.map(
      (v) => `| \`${v.txHash.slice(0, 10)}…\` | ${v.chainKey} | ${v.anchor} | ${v.continuityRoots} | ${v.ok ? int(v.gas) : "refused"} |`,
    ),
    "",
    `- ${fit(m.anchors.verifyFit, "continuity roots", "verify gas")}.`,
    "",
    "### Attestation latency",
    "",
    `Seconds from a World ID update's source block to its root landing on Creditcoin, per root, over ${m.latency.spanHours.toFixed(1)} hours of relay history.`,
    "",
    "| Relay | Roots | Min | Median | p90 | Max |",
    "|---|---:|---:|---:|---:|---:|",
    summaryRow("both", m.latency.summary, dur),
    ...Object.entries(m.latency.byRelay).map(([name, s]) => summaryRow(name, s, dur)),
    "",
    "### Proof size",
    "",
    "| Measure | Samples | Min | Median | p90 | Max |",
    "|---|---:|---:|---:|---:|---:|",
    summaryRow("relay calldata (bytes)", m.proofSizes.calldata, int),
    summaryRow("encoded source tx (bytes)", m.proofSizes.txBytes, int),
    summaryRow("continuity roots per proof", m.proofSizes.continuityRoots, int),
    "",
    "Calldata distribution (2 KB buckets):",
    "",
    "| Bytes | Transactions |",
    "|---|---:|",
    ...m.proofSizes.histogram.filter((b) => b.count > 0).map((b) => `| ${int(b.from)}–${int(b.to)} | ${b.count} |`),
    "",
    "### Who uses the BlockProver precompile",
    "",
    `Every \`0x0FD2\` log in CC3 blocks ${int(m.precompile.fromBlock)}–${int(m.precompile.toBlock)} (${m.precompile.hours.toFixed(1)} h): ${int(m.precompile.logs)} logs in ${int(m.precompile.txs)} transactions to ${m.precompile.callers.length} distinct contracts. Humanline sent ${int(m.precompile.humanlineTxs)} of them (${pct(m.precompile.humanlineShare)}).`,
    "",
    "| Called contract | Transactions | Share | Humanline |",
    "|---|---:|---:|---|",
    ...m.precompile.callers
      .slice(0, 12)
      .map((c) => `| ${short(c.to)} | ${int(c.txs)} | ${pct(m.precompile.txs ? c.txs / m.precompile.txs : 0)} | ${c.humanline ? "yes" : ""} |`),
    "",
    END,
  );
  return lines.join("\n");
}

/** Replace the generated block in a document, or append it when the markers are absent. */
export function spliceMeasurements(doc: string, rendered: string): string {
  const start = doc.indexOf(START.slice(0, 26));
  const end = doc.indexOf(END);
  if (start >= 0 && end > start) return `${doc.slice(0, start)}${rendered}${doc.slice(end + END.length)}`;
  return `${doc.trimEnd()}\n\n${rendered}\n`;
}
